version: "3"
services:
  exchanges_parser:
    image: 0xfar5eer/rs-exchanges-parser:release
    restart: always
    environment:
      MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@db:27017
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_COLLECTION_EXCHANGES: ${MONGODB_COLLECTION_EXCHANGES}
    build:
      context: .
      dockerfile: rs-exchanges-parser.Dockerfile
    # ports:
    #   - "3000:64001"
    depends_on:
      - db
  db:
    image: mongo:6.0
    # image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "64001:27017"
    volumes:
      - db:/var/lib/mongodb/data_4.4.18

volumes:
  db:
    driver: local
