[package]
name = "rs-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.20", features = ["json"] }
tokio = { version = "1.32.0", features = ["default"] }
mongodb = "2.6.1"
serde = "1.0.188"
serde_json = "1.0.107"
chrono = "0.4.31"
bson = "2.7.0"
futures = "0.3.28"
log = "0.4.20"
fern = "0.6.2"
env_logger = "0.10.0"
log-panics = "2.1.0"
dotenvy = "0.15.7"
